### ISSUE TITLE
The ground truth for the real data sets

### ISSUE THREAD

**Issue by mourisl** [tAndreani/scBCR#5]
Greetings. Thanks for conducting this study to comprehensively evaluate the performance of the methods on BCR reconstruction. As the developer of TRUST4, I believe there are still a lot of potential improvements for TRUST4 on SMART-seq data. Your work is a very valuable resource for the method development, and I'm wondering whether it is possible to share the ground truth you generated for the real data sets on github? I'm particularly interested in the Upadhyay data, but other users/developers may be interested in other samples. Thank you!

**Comment by tAndreani** [comment]
Hello,  

thank you for the messagge and thank you again for provide TRUST4 to the community. 

It is possible to find the ground truth information of all the datasets on the folder  https://github.com/tAndreani/scBCR/tree/main/Real_Data/Ground_Truth

Let me know if you need more information. 
Best Regards

**Comment by mourisl** [comment]
This looks great! Thank you very much.

**Comment by mourisl** [comment]
Thanks for providing the ground truth data. I have compared the results from TRUST4 with the results you provided on the Upadhyay. The match rate on the heavy chains is much higher in my comparison. For example, all the 34 CDR3 nucleotide sequences are found and 30 of them have matched V and J genes. 

After looking into this issue, I noticed that in your paper and the script, it seems the match with ground truth is solely based on V, D, J gene assignment. I think this may cause some bias to the methods that have their own VDJ annotation method, such as TRUST4 and MiXCR. In particular, since the D gene is quite short, it is very hard to define the correct one. For example, when considering D gene match, TRUST4's match rate is about 19 out of 34 which matches the number from your paper. Furthermore, depending on the IMGT database version, the allele id could also be different. For example for the IGHV gene mismatches from TRUST4, all 3 of them are just differ by allele number (For example F7 has IGHV1-69*01,IGHV1-69*12,IGHV1-69*13 as ground truth and TRUST4 says IGHV1-69*08). For the remaining case of TRUST4's mismatch J gene, it is on sample E10, and the ground truth has IGHJ4*02 while TRUST4 uses IGHJ6 as the primary J gene and IGHJ4*02 at the secondary guess ( IGHJ6 has lower the match rate but it has longer hits) ). 

In summary, I found that the low match rate for methods like TRUST4, MiXCR may arise due to the annotation procedure. BASIC does not have annotation, so the annotation uses same procedure as the way of ground truth generation. BALDR uses IgBLAST for the annotation which is essentially the same as the ground truth. I would suggest use the same approach to annotate TRUST4 and MiXCR's output (I'm not familiar with VDJPuzzle and BRACER's output) with immancation. You may also need to handle the case of allele mismatch or several equivalent good gene assignment but on different order. The best way to define the match with the ground truth is checking whether the VDJ sequences are identical, or at least it should be V+J+isotype+CDR3 sequence instead of just V+D+J gene match. For example, the full sequence of E10 ground truth is a substring of TRUST4's assembled sequence, so it definitely should be considered as a match.

Sorry for the long message, hope my understanding of your evaluation criteria is correct and these comments could be helpful on future evaluations. Thank you.

**Comment by tAndreani** [comment]
Thank you for confirming what already done and identify the D gene mis-hit problem for TRUST4 and MiXCR. Glad that your results are indeed in line with what I have found.

I have some considerations:

First, the match of the genes in our benchmark indeed considers the multiple alleles. Which means, if a tool annotated the gene e.g. IGHV1-6901 and the ground truth igblast output annotate the gene(s) IGHV1-6901,IGHV1-6910 this is considered as a match and not a mis-hits. We were aware of this and explained in the chapter related to the calculation of the sensitivity.

Second, MiXCR has been already published as the tool with the highest amount of mis-hits in this nice benchmark solely intended for evaluate the accuracy of the alignment of the V-(D)-J genes based on IMGT annotation [here](https://academic.oup.com/bioinformatics/article/36/6/1731/5686386?login=true). When I started the benchamark, I tried to merge the CDR1-2-3 and the FWR1-2-3-4 of the output and and run Igbalst to re-annotate the genes but i have noticed not differences between the genes assigned by MiXCR and IgBlast output. 

Third, MiXCR uses the IMGT annotation. Isnt the same for TRUST4? This is at least what is written on your paper in the supplementary Methods section - Annotation paragraph. Please correct me if I am wrong.

All your points above are of importance and for sure will need to be considered for future benchmark. We think that an additional invaluable benchmark would be one solely based on the reference annotation so to ask the question: how different the reconstruction of BCR is when using different annotation database?

In addition to your statement: 

"The best way to define the match with the ground truth is checking whether the VDJ sequences are identical, or at least it should be V+J+isotype+CDR3 sequence instead of just V+D+J gene match."

I partially agree with you. If you are familiar with Sanger sequencing, you might have several errors at the sequence level during the sequencing which can create single nucleotide polymorphism into the sequence. It is indeed not by chance that all the 3 gound truth had only ~40% of the single cells with paired HC+LC sequenced mostly due to mutations (artificial) that either cause stop codons or frame-shifts. This is why we opted to use the "gene-level" strategy and not the sequence level. Also, at the gene level, if an allele is not present in IMGT it wont be annotated by the tools (given that they use IMGT) nor by IgBlast.

Thank you again for your considerations and I hope my argumentation on the evaluation criteria make sense to you. I hope our comments will guide/help other people in the BCR community.

**Comment by mourisl** [comment]
Thanks for the explanations! I now understand most of the decisions.

A few minor points:
1) For the allele id, will IGHV1-69\*01 match with IGHV1-69\*02 ? 
2) Yes, TRUST4 also uses IMGT annotation database. But IMGT also has version changes, and this may cause some inconsistency, especially on allele ids.

**Comment by tAndreani** [comment]
Sorry late reply. Regarding your questions:

1) IGHV1-69*01 vs IGHV1-69*02 are not considered as a match. Even if they are same genes the allele is different. In the case a tool would have obtained a BCR with IGHV1-69*01 gene/allele and the ground truth IGHV1-69*01,IGHV1-69*02 this would have been a match because at least one allele of the two (either in Ground Truth or in the BCR reconstructed by the tool) has a match;
 
2) all the BCR sequences (HC and LC) reconstructed by the tools were annotated using the same immcantation version. The tools used for reconstrcut the BCR were the most updated at the moment of starting the benchmark;

I hope this helps.

**Comment by tAndreani** [comment]
I close this issue @mourisl feel free to re-open it.

**Comment by mourisl** [comment]
Thank you for getting back to me. Congratulations on the publication!
